/**
 * Generated by tools/logos/build-logos.ts — do not edit by hand.
 *
 * The most recognizable global brands, in Interbrand Best Global Brands 2025
 * order, that have a premium full-color brand SVG. Every entry has both files
 * on disk under apps/web/public.
 */
export type Company = {
  readonly rank: number;
  /** Stock ticker, when the brand is itself a listed company. */
  readonly ticker?: string;
  readonly name: string;
  readonly slug: string;
  readonly svgPath: string;
  readonly gainmapPath: string;
  readonly sdrPath: string;
};

export const COMPANIES: readonly Company[] = [
  { rank: 1, name: "Apple", slug: "apple", svgPath: "/logos/apple/logo.svg", gainmapPath: "/logos/apple/logo-gainmap.jpg", sdrPath: "/logos/apple/logo-sdr.jpg" },
  { rank: 2, name: "Microsoft", slug: "microsoft", svgPath: "/logos/microsoft/logo.svg", gainmapPath: "/logos/microsoft/logo-gainmap.jpg", sdrPath: "/logos/microsoft/logo-sdr.jpg" },
  { rank: 3, name: "Amazon", slug: "amazon", svgPath: "/logos/amazon/logo.svg", gainmapPath: "/logos/amazon/logo-gainmap.jpg", sdrPath: "/logos/amazon/logo-sdr.jpg" },
  { rank: 4, name: "Google", slug: "google", svgPath: "/logos/google/logo.svg", gainmapPath: "/logos/google/logo-gainmap.jpg", sdrPath: "/logos/google/logo-sdr.jpg" },
  { rank: 5, name: "Samsung", slug: "samsung", svgPath: "/logos/samsung/logo.svg", gainmapPath: "/logos/samsung/logo-gainmap.jpg", sdrPath: "/logos/samsung/logo-sdr.jpg" },
  { rank: 6, name: "Toyota", slug: "toyota", svgPath: "/logos/toyota/logo.svg", gainmapPath: "/logos/toyota/logo-gainmap.jpg", sdrPath: "/logos/toyota/logo-sdr.jpg" },
  { rank: 7, name: "Coca-Cola", slug: "coca-cola", svgPath: "/logos/coca-cola/logo.svg", gainmapPath: "/logos/coca-cola/logo-gainmap.jpg", sdrPath: "/logos/coca-cola/logo-sdr.jpg" },
  { rank: 8, name: "Instagram", slug: "instagram", svgPath: "/logos/instagram/logo.svg", gainmapPath: "/logos/instagram/logo-gainmap.jpg", sdrPath: "/logos/instagram/logo-sdr.jpg" },
  { rank: 9, name: "Louis Vuitton", slug: "louis-vuitton", svgPath: "/logos/louis-vuitton/logo.svg", gainmapPath: "/logos/louis-vuitton/logo-gainmap.jpg", sdrPath: "/logos/louis-vuitton/logo-sdr.jpg" },
  { rank: 10, name: "Tesla", slug: "tesla", svgPath: "/logos/tesla/logo.svg", gainmapPath: "/logos/tesla/logo-gainmap.jpg", sdrPath: "/logos/tesla/logo-sdr.jpg" },
  { rank: 11, name: "Hermès", slug: "hermes", svgPath: "/logos/hermes/logo.svg", gainmapPath: "/logos/hermes/logo-gainmap.jpg", sdrPath: "/logos/hermes/logo-sdr.jpg" },
  { rank: 12, name: "Nike", slug: "nike", svgPath: "/logos/nike/logo.svg", gainmapPath: "/logos/nike/logo-gainmap.jpg", sdrPath: "/logos/nike/logo-sdr.jpg" },
  { rank: 13, name: "YouTube", slug: "youtube", svgPath: "/logos/youtube/logo.svg", gainmapPath: "/logos/youtube/logo-gainmap.jpg", sdrPath: "/logos/youtube/logo-sdr.jpg" },
  { rank: 14, name: "BMW", slug: "bmw", svgPath: "/logos/bmw/logo.svg", gainmapPath: "/logos/bmw/logo-gainmap.jpg", sdrPath: "/logos/bmw/logo-sdr.jpg" },
  { rank: 15, name: "Mercedes-Benz", slug: "mercedes-benz", svgPath: "/logos/mercedes-benz/logo.svg", gainmapPath: "/logos/mercedes-benz/logo-gainmap.jpg", sdrPath: "/logos/mercedes-benz/logo-sdr.jpg" },
  { rank: 16, name: "Disney", slug: "disney", svgPath: "/logos/disney/logo.svg", gainmapPath: "/logos/disney/logo-gainmap.jpg", sdrPath: "/logos/disney/logo-sdr.jpg" },
  { rank: 17, name: "Chanel", slug: "chanel", svgPath: "/logos/chanel/logo.svg", gainmapPath: "/logos/chanel/logo-gainmap.jpg", sdrPath: "/logos/chanel/logo-sdr.jpg" },
  { rank: 18, name: "SAP", slug: "sap", svgPath: "/logos/sap/logo.svg", gainmapPath: "/logos/sap/logo-gainmap.jpg", sdrPath: "/logos/sap/logo-sdr.jpg" },
  { rank: 19, name: "Facebook", slug: "facebook", svgPath: "/logos/facebook/logo.svg", gainmapPath: "/logos/facebook/logo-gainmap.jpg", sdrPath: "/logos/facebook/logo-sdr.jpg" },
  { rank: 20, name: "Honda", slug: "honda", svgPath: "/logos/honda/logo.svg", gainmapPath: "/logos/honda/logo-gainmap.jpg", sdrPath: "/logos/honda/logo-sdr.jpg" },
  { rank: 21, name: "Gucci", slug: "gucci", svgPath: "/logos/gucci/logo.svg", gainmapPath: "/logos/gucci/logo-gainmap.jpg", sdrPath: "/logos/gucci/logo-sdr.jpg" },
  { rank: 22, name: "Porsche", slug: "porsche", svgPath: "/logos/porsche/logo.svg", gainmapPath: "/logos/porsche/logo-gainmap.jpg", sdrPath: "/logos/porsche/logo-sdr.jpg" },
  { rank: 23, name: "Accenture", slug: "accenture", svgPath: "/logos/accenture/logo.svg", gainmapPath: "/logos/accenture/logo-gainmap.jpg", sdrPath: "/logos/accenture/logo-sdr.jpg" },
  { rank: 24, name: "Zara", slug: "zara", svgPath: "/logos/zara/logo.svg", gainmapPath: "/logos/zara/logo-gainmap.jpg", sdrPath: "/logos/zara/logo-sdr.jpg" },
  { rank: 25, name: "Spotify", slug: "spotify", svgPath: "/logos/spotify/logo.svg", gainmapPath: "/logos/spotify/logo-gainmap.jpg", sdrPath: "/logos/spotify/logo-sdr.jpg" },
  { rank: 26, name: "IKEA", slug: "ikea", svgPath: "/logos/ikea/logo.svg", gainmapPath: "/logos/ikea/logo-gainmap.jpg", sdrPath: "/logos/ikea/logo-sdr.jpg" },
  { rank: 27, name: "Nescafé", slug: "nescafe", svgPath: "/logos/nescafe/logo.svg", gainmapPath: "/logos/nescafe/logo-gainmap.jpg", sdrPath: "/logos/nescafe/logo-sdr.jpg" },
  { rank: 28, name: "ALDI", slug: "aldi", svgPath: "/logos/aldi/logo.svg", gainmapPath: "/logos/aldi/logo-gainmap.jpg", sdrPath: "/logos/aldi/logo-sdr.jpg" },
  { rank: 29, name: "LinkedIn", slug: "linkedin", svgPath: "/logos/linkedin/logo.svg", gainmapPath: "/logos/linkedin/logo-gainmap.jpg", sdrPath: "/logos/linkedin/logo-sdr.jpg" },
  { rank: 30, name: "J.P. Morgan", slug: "jpmorgan", svgPath: "/logos/jpmorgan/logo.svg", gainmapPath: "/logos/jpmorgan/logo-gainmap.jpg", sdrPath: "/logos/jpmorgan/logo-sdr.jpg" },
  { rank: 31, name: "Prada", slug: "prada", svgPath: "/logos/prada/logo.svg", gainmapPath: "/logos/prada/logo-gainmap.jpg", sdrPath: "/logos/prada/logo-sdr.jpg" },
  { rank: 32, name: "Goldman Sachs", slug: "goldman-sachs", svgPath: "/logos/goldman-sachs/logo.svg", gainmapPath: "/logos/goldman-sachs/logo-gainmap.jpg", sdrPath: "/logos/goldman-sachs/logo-sdr.jpg" },
  { rank: 33, name: "Hyundai", slug: "hyundai", svgPath: "/logos/hyundai/logo.svg", gainmapPath: "/logos/hyundai/logo-gainmap.jpg", sdrPath: "/logos/hyundai/logo-sdr.jpg" },
  { rank: 34, name: "Mastercard", slug: "mastercard", svgPath: "/logos/mastercard/logo.svg", gainmapPath: "/logos/mastercard/logo-gainmap.jpg", sdrPath: "/logos/mastercard/logo-sdr.jpg" },
  { rank: 35, name: "Pampers", slug: "pampers", svgPath: "/logos/pampers/logo.svg", gainmapPath: "/logos/pampers/logo-gainmap.jpg", sdrPath: "/logos/pampers/logo-sdr.jpg" },
  { rank: 36, name: "Kia", slug: "kia", svgPath: "/logos/kia/logo.svg", gainmapPath: "/logos/kia/logo-gainmap.jpg", sdrPath: "/logos/kia/logo-sdr.jpg" },
  { rank: 37, name: "Red Bull", slug: "red-bull", svgPath: "/logos/red-bull/logo.svg", gainmapPath: "/logos/red-bull/logo-gainmap.jpg", sdrPath: "/logos/red-bull/logo-sdr.jpg" },
  { rank: 38, name: "Pepsi", slug: "pepsi", svgPath: "/logos/pepsi/logo.svg", gainmapPath: "/logos/pepsi/logo-gainmap.jpg", sdrPath: "/logos/pepsi/logo-sdr.jpg" },
  { rank: 39, name: "Netflix", slug: "netflix", svgPath: "/logos/netflix/logo.svg", gainmapPath: "/logos/netflix/logo-gainmap.jpg", sdrPath: "/logos/netflix/logo-sdr.jpg" },
  { rank: 40, name: "Shell", slug: "shell", svgPath: "/logos/shell/logo.svg", gainmapPath: "/logos/shell/logo-gainmap.jpg", sdrPath: "/logos/shell/logo-sdr.jpg" },
  { rank: 41, name: "Volkswagen", slug: "volkswagen", svgPath: "/logos/volkswagen/logo.svg", gainmapPath: "/logos/volkswagen/logo-gainmap.jpg", sdrPath: "/logos/volkswagen/logo-sdr.jpg" },
  { rank: 42, name: "Salesforce", slug: "salesforce", svgPath: "/logos/salesforce/logo.svg", gainmapPath: "/logos/salesforce/logo-gainmap.jpg", sdrPath: "/logos/salesforce/logo-sdr.jpg" },
  { rank: 43, name: "AXA", slug: "axa", svgPath: "/logos/axa/logo.svg", gainmapPath: "/logos/axa/logo-gainmap.jpg", sdrPath: "/logos/axa/logo-sdr.jpg" },
  { rank: 44, name: "L'Oréal", slug: "loreal", svgPath: "/logos/loreal/logo.svg", gainmapPath: "/logos/loreal/logo-gainmap.jpg", sdrPath: "/logos/loreal/logo-sdr.jpg" },
  { rank: 45, name: "Gillette", slug: "gillette", svgPath: "/logos/gillette/logo.svg", gainmapPath: "/logos/gillette/logo-gainmap.jpg", sdrPath: "/logos/gillette/logo-sdr.jpg" },
  { rank: 46, name: "Huawei", slug: "huawei", svgPath: "/logos/huawei/logo.svg", gainmapPath: "/logos/huawei/logo-gainmap.jpg", sdrPath: "/logos/huawei/logo-sdr.jpg" },
  { rank: 47, name: "UNIQLO", slug: "uniqlo", svgPath: "/logos/uniqlo/logo.svg", gainmapPath: "/logos/uniqlo/logo-gainmap.jpg", sdrPath: "/logos/uniqlo/logo-sdr.jpg" },
  { rank: 48, name: "Nespresso", slug: "nespresso", svgPath: "/logos/nespresso/logo.svg", gainmapPath: "/logos/nespresso/logo-gainmap.jpg", sdrPath: "/logos/nespresso/logo-sdr.jpg" },
  { rank: 49, name: "Audi", slug: "audi", svgPath: "/logos/audi/logo.svg", gainmapPath: "/logos/audi/logo-gainmap.jpg", sdrPath: "/logos/audi/logo-sdr.jpg" },
  { rank: 50, name: "LEGO", slug: "lego", svgPath: "/logos/lego/logo.svg", gainmapPath: "/logos/lego/logo-gainmap.jpg", sdrPath: "/logos/lego/logo-sdr.jpg" },
  { rank: 51, name: "Adidas", slug: "adidas", svgPath: "/logos/adidas/logo.svg", gainmapPath: "/logos/adidas/logo-gainmap.jpg", sdrPath: "/logos/adidas/logo-sdr.jpg" },
  { rank: 52, name: "Cartier", slug: "cartier", svgPath: "/logos/cartier/logo.svg", gainmapPath: "/logos/cartier/logo-gainmap.jpg", sdrPath: "/logos/cartier/logo-sdr.jpg" },
  { rank: 53, name: "Nintendo", slug: "nintendo", svgPath: "/logos/nintendo/logo.svg", gainmapPath: "/logos/nintendo/logo-gainmap.jpg", sdrPath: "/logos/nintendo/logo-sdr.jpg" },
  { rank: 54, name: "Allianz", slug: "allianz", svgPath: "/logos/allianz/logo.svg", gainmapPath: "/logos/allianz/logo-gainmap.jpg", sdrPath: "/logos/allianz/logo-sdr.jpg" },
  { rank: 55, name: "Range Rover", slug: "range-rover", svgPath: "/logos/range-rover/logo.svg", gainmapPath: "/logos/range-rover/logo-gainmap.jpg", sdrPath: "/logos/range-rover/logo-sdr.jpg" },
  { rank: 56, name: "PayPal", slug: "paypal", svgPath: "/logos/paypal/logo.svg", gainmapPath: "/logos/paypal/logo-gainmap.jpg", sdrPath: "/logos/paypal/logo-sdr.jpg" },
  { rank: 57, name: "Rolex", slug: "rolex", svgPath: "/logos/rolex/logo.svg", gainmapPath: "/logos/rolex/logo-gainmap.jpg", sdrPath: "/logos/rolex/logo-sdr.jpg" },
  { rank: 58, name: "Zoom", slug: "zoom", svgPath: "/logos/zoom/logo.svg", gainmapPath: "/logos/zoom/logo-gainmap.jpg", sdrPath: "/logos/zoom/logo-sdr.jpg" },
  { rank: 59, name: "Visa", slug: "visa", svgPath: "/logos/visa/logo.svg", gainmapPath: "/logos/visa/logo-gainmap.jpg", sdrPath: "/logos/visa/logo-sdr.jpg" },
  { rank: 60, name: "Tiffany & Co.", slug: "tiffany", svgPath: "/logos/tiffany/logo.svg", gainmapPath: "/logos/tiffany/logo-gainmap.jpg", sdrPath: "/logos/tiffany/logo-sdr.jpg" },
  { rank: 61, name: "Caterpillar", slug: "caterpillar", svgPath: "/logos/caterpillar/logo.svg", gainmapPath: "/logos/caterpillar/logo-gainmap.jpg", sdrPath: "/logos/caterpillar/logo-sdr.jpg" },
  { rank: 62, name: "Siemens", slug: "siemens", svgPath: "/logos/siemens/logo.svg", gainmapPath: "/logos/siemens/logo-gainmap.jpg", sdrPath: "/logos/siemens/logo-sdr.jpg" },
  { rank: 63, name: "Dior", slug: "dior", svgPath: "/logos/dior/logo.svg", gainmapPath: "/logos/dior/logo-gainmap.jpg", sdrPath: "/logos/dior/logo-sdr.jpg" },
  { rank: 64, name: "WeChat", slug: "wechat", svgPath: "/logos/wechat/logo.svg", gainmapPath: "/logos/wechat/logo-gainmap.jpg", sdrPath: "/logos/wechat/logo-sdr.jpg" },
  { rank: 65, name: "Lexus", slug: "lexus", svgPath: "/logos/lexus/logo.svg", gainmapPath: "/logos/lexus/logo-gainmap.jpg", sdrPath: "/logos/lexus/logo-sdr.jpg" },
  { rank: 66, name: "Budweiser", slug: "budweiser", svgPath: "/logos/budweiser/logo.svg", gainmapPath: "/logos/budweiser/logo-gainmap.jpg", sdrPath: "/logos/budweiser/logo-sdr.jpg" },
  { rank: 67, name: "Lamborghini", slug: "lamborghini", svgPath: "/logos/lamborghini/logo.svg", gainmapPath: "/logos/lamborghini/logo-gainmap.jpg", sdrPath: "/logos/lamborghini/logo-sdr.jpg" },
  { rank: 68, name: "Renault", slug: "renault", svgPath: "/logos/renault/logo.svg", gainmapPath: "/logos/renault/logo-gainmap.jpg", sdrPath: "/logos/renault/logo-sdr.jpg" },
  { rank: 69, name: "Puma", slug: "puma", svgPath: "/logos/puma/logo.svg", gainmapPath: "/logos/puma/logo-gainmap.jpg", sdrPath: "/logos/puma/logo-sdr.jpg" },
  { rank: 71, name: "Burberry", slug: "burberry", svgPath: "/logos/burberry/logo.svg", gainmapPath: "/logos/burberry/logo-gainmap.jpg", sdrPath: "/logos/burberry/logo-sdr.jpg" },
  { rank: 72, name: "HSBC", slug: "hsbc", svgPath: "/logos/hsbc/logo.svg", gainmapPath: "/logos/hsbc/logo-gainmap.jpg", sdrPath: "/logos/hsbc/logo-sdr.jpg" },
  { rank: 73, name: "3M", slug: "3m", svgPath: "/logos/3m/logo.svg", gainmapPath: "/logos/3m/logo-gainmap.jpg", sdrPath: "/logos/3m/logo-sdr.jpg" },
  { rank: 74, name: "Philips", slug: "philips", svgPath: "/logos/philips/logo.svg", gainmapPath: "/logos/philips/logo-gainmap.jpg", sdrPath: "/logos/philips/logo-sdr.jpg" },
  { rank: 75, name: "Ferrari", slug: "ferrari", svgPath: "/logos/ferrari/logo.svg", gainmapPath: "/logos/ferrari/logo-gainmap.jpg", sdrPath: "/logos/ferrari/logo-sdr.jpg" },
  { rank: 76, name: "Colgate", slug: "colgate", svgPath: "/logos/colgate/logo.svg", gainmapPath: "/logos/colgate/logo-gainmap.jpg", sdrPath: "/logos/colgate/logo-sdr.jpg" },
  { rank: 77, name: "Hennessy", slug: "hennessy", svgPath: "/logos/hennessy/logo.svg", gainmapPath: "/logos/hennessy/logo-gainmap.jpg", sdrPath: "/logos/hennessy/logo-sdr.jpg" },
  { rank: 78, name: "Kellogg's", slug: "kelloggs", svgPath: "/logos/kelloggs/logo.svg", gainmapPath: "/logos/kelloggs/logo-gainmap.jpg", sdrPath: "/logos/kelloggs/logo-sdr.jpg" },
  { rank: 79, name: "Jeep", slug: "jeep", svgPath: "/logos/jeep/logo.svg", gainmapPath: "/logos/jeep/logo-gainmap.jpg", sdrPath: "/logos/jeep/logo-sdr.jpg" },
  { rank: 80, name: "FedEx", slug: "fedex", svgPath: "/logos/fedex/logo.svg", gainmapPath: "/logos/fedex/logo-gainmap.jpg", sdrPath: "/logos/fedex/logo-sdr.jpg" },
  { rank: 81, name: "Xiaomi", slug: "xiaomi", svgPath: "/logos/xiaomi/logo.svg", gainmapPath: "/logos/xiaomi/logo-gainmap.jpg", sdrPath: "/logos/xiaomi/logo-sdr.jpg" },
  { rank: 82, name: "Panasonic", slug: "panasonic", svgPath: "/logos/panasonic/logo.svg", gainmapPath: "/logos/panasonic/logo-gainmap.jpg", sdrPath: "/logos/panasonic/logo-sdr.jpg" },
  { rank: 83, name: "Ralph Lauren", slug: "ralph-lauren", svgPath: "/logos/ralph-lauren/logo.svg", gainmapPath: "/logos/ralph-lauren/logo-gainmap.jpg", sdrPath: "/logos/ralph-lauren/logo-sdr.jpg" },
  { rank: 84, name: "Jack Daniel's", slug: "jack-daniels", svgPath: "/logos/jack-daniels/logo.svg", gainmapPath: "/logos/jack-daniels/logo-gainmap.jpg", sdrPath: "/logos/jack-daniels/logo-sdr.jpg" },
  { rank: 86, name: "Corona", slug: "corona", svgPath: "/logos/corona/logo.svg", gainmapPath: "/logos/corona/logo-gainmap.jpg", sdrPath: "/logos/corona/logo-sdr.jpg" },
  { rank: 87, name: "John Deere", slug: "john-deere", svgPath: "/logos/john-deere/logo.svg", gainmapPath: "/logos/john-deere/logo-gainmap.jpg", sdrPath: "/logos/john-deere/logo-sdr.jpg" },
  { rank: 88, name: "DHL", slug: "dhl", svgPath: "/logos/dhl/logo.svg", gainmapPath: "/logos/dhl/logo-gainmap.jpg", sdrPath: "/logos/dhl/logo-sdr.jpg" },
  { rank: 89, name: "Henkel", slug: "henkel", svgPath: "/logos/henkel/logo.svg", gainmapPath: "/logos/henkel/logo-gainmap.jpg", sdrPath: "/logos/henkel/logo-sdr.jpg" },
  { rank: 90, name: "Harley-Davidson", slug: "harley-davidson", svgPath: "/logos/harley-davidson/logo.svg", gainmapPath: "/logos/harley-davidson/logo-gainmap.jpg", sdrPath: "/logos/harley-davidson/logo-sdr.jpg" },
  { rank: 91, name: "Nestlé", slug: "nestle", svgPath: "/logos/nestle/logo.svg", gainmapPath: "/logos/nestle/logo-gainmap.jpg", sdrPath: "/logos/nestle/logo-sdr.jpg" },
  { rank: 92, name: "Heineken", slug: "heineken", svgPath: "/logos/heineken/logo.svg", gainmapPath: "/logos/heineken/logo-gainmap.jpg", sdrPath: "/logos/heineken/logo-sdr.jpg" },
  { rank: 93, name: "Xerox", slug: "xerox", svgPath: "/logos/xerox/logo.svg", gainmapPath: "/logos/xerox/logo-gainmap.jpg", sdrPath: "/logos/xerox/logo-sdr.jpg" },
  { rank: 94, name: "Adobe", slug: "adobe", svgPath: "/logos/adobe/logo.svg", gainmapPath: "/logos/adobe/logo-gainmap.jpg", sdrPath: "/logos/adobe/logo-sdr.jpg" },
  { rank: 95, name: "Subaru", slug: "subaru", svgPath: "/logos/subaru/logo.svg", gainmapPath: "/logos/subaru/logo-gainmap.jpg", sdrPath: "/logos/subaru/logo-sdr.jpg" },
  { rank: 96, name: "H&M", slug: "h-and-m", svgPath: "/logos/h-and-m/logo.svg", gainmapPath: "/logos/h-and-m/logo-gainmap.jpg", sdrPath: "/logos/h-and-m/logo-sdr.jpg" },
  { rank: 97, name: "Morgan Stanley", slug: "morgan-stanley", svgPath: "/logos/morgan-stanley/logo.svg", gainmapPath: "/logos/morgan-stanley/logo-gainmap.jpg", sdrPath: "/logos/morgan-stanley/logo-sdr.jpg" },
  { rank: 98, name: "Duracell", slug: "duracell", svgPath: "/logos/duracell/logo.svg", gainmapPath: "/logos/duracell/logo-gainmap.jpg", sdrPath: "/logos/duracell/logo-sdr.jpg" },
  { rank: 99, name: "Shopify", slug: "shopify", svgPath: "/logos/shopify/logo.svg", gainmapPath: "/logos/shopify/logo-gainmap.jpg", sdrPath: "/logos/shopify/logo-sdr.jpg" },
  { rank: 100, name: "UPS", slug: "ups", svgPath: "/logos/ups/logo.svg", gainmapPath: "/logos/ups/logo-gainmap.jpg", sdrPath: "/logos/ups/logo-sdr.jpg" },
  { rank: 101, name: "American Express", slug: "american-express", svgPath: "/logos/american-express/logo.svg", gainmapPath: "/logos/american-express/logo-gainmap.jpg", sdrPath: "/logos/american-express/logo-sdr.jpg" },
  { rank: 102, name: "Starbucks", slug: "starbucks", svgPath: "/logos/starbucks/logo.svg", gainmapPath: "/logos/starbucks/logo-gainmap.jpg", sdrPath: "/logos/starbucks/logo-sdr.jpg" },
];

export function companyBySlug(slug: string): Company | undefined {
  return COMPANIES.find((company) => company.slug === slug);
}

export function logoSdrSrcset(company: Company): string {
  return [128, 256, 512, 1024].map(w => `/logos/${company.slug}/logo-sdr-${w}.jpg ${w}w`).join(", ");
}

export function logoGainmapSrcset(company: Company): string {
  return [128, 256, 512, 1024].map(w => `/logos/${company.slug}/logo-gainmap-${w}.jpg ${w}w`).join(", ");
}
